- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /_db
  script: _db.py

- url: /scrape
  script: scrape.py

- url: /get
  script: get.py

- url: /test
  script: test.py

## MODE SWITCHING -- DON'T MESS WITH (unless you know what you're doing)!
# START mode: dynamic
#- url: /js
#  static_dir: js
#- url: /.*\.html
#  static_dir: html
# END mode: dynamic
# START mode: static
#- url: /js
#  static_dir: js
#- url: /.*\.html
#  static_dir: html-static
# END mode: static
# START mode: production
- url: /.*\.html
  static_dir: html-production
# END mode: production